"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const api_login_js_1 = require("./api_login.js");
const api_tarefas_js_1 = require("./api_tarefas.js");
const api_admin_js_1 = require("./api_admin.js");
const app = (0, express_1.default)();
const router = express_1.default.Router();
app.use(express_1.default.json());
router.get('/', (req, res) => {
    res.send("api rodando");
});
router.post('/login/google', api_login_js_1.Login_via_Google);
router.post('/login', api_login_js_1.Login_via_Email);
router.post('/cadastro', api_login_js_1.Cadastro);
router.post('/tarefas', api_tarefas_js_1.adicionar_tarefa);
router.put('/tarefas', api_tarefas_js_1.editar_tarefa);
router.delete('/tarefas', api_tarefas_js_1.excluir_tarefa);
router.post('/tarefas/concluir', api_tarefas_js_1.concluir_tarefa);
router.post('/tarefas/get', api_tarefas_js_1.get_tarefa);
router.post('/tarefas/get/all', api_tarefas_js_1.get_tarefas);
router.post('/admin', api_admin_js_1.adicionar_admin);
router.post('/admin/get', api_admin_js_1.get_usuarios);
router.post('/admin/get/all', api_admin_js_1.get_all_tarefas);
router.post('/admin/get/tarefas', api_admin_js_1.get_tarefas_usuario);
router.post('/admin/get/tarefas/pendentes', api_admin_js_1.get_tarefas_pendentes);
router.post('/admin/get/tarefas/concluidas', api_admin_js_1.get_tarefas_concluidas);
router.post('/admin/get/tarefas/atrasadas', api_admin_js_1.get_tarefas_atrasadas);
exports.default = router;
